### ISSUE TITLE
Fantom Runtime is not building with Java 1.8

### ISSUE THREAD

**Issue by haiodo** [xored/fantom-runtime#2]

**Comment by SlimerDude** [comment]
Is this related to [#1765 Building Fantom using Oracle JDK 7 fails with "javac: target release 1.5 conflicts with default source release 1.7"](http://fantom.org/forum/topic/1765#c18)? If so, the fix was to alter the following property in `%FAN_HOME%/etc/build/config.props`:

```
// JVM version compiler target, by default Fantom requires a JDK 1.6
// compiler that targets 1.5.  To use JDK 1.7, this property needs to
// be cleared or set the env var FAN_BUILD_JAVACPARAMS to a space
javacParams=-target 1.5
```
